export const chairs = [
  {
    id: 1,
    name: "Avery Accent Chair",
    description:
      "A mid-century modern chair with plush cushioning and a sleek oak frame.",
    price: 159.99,
    discount: 20,
    image: "/images/chair/chair1.webp",
    category: "chair",
    stock: 8,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Luna Lounge Chair",
    description:
      "Low-profile chair with a wide seat and soft linen upholstery for maximum comfort.",
    price: 189.99,
    discount: 20,
    image: "/images/chair/chair2.webp",
    category: "chair",
    stock: 12,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 3,
    name: "Oslo Dining Chair",
    description:
      "Scandinavian-style dining chair made from solid birch and padded with vegan leather.",
    price: 99.99,
    discount: 0,
    image: "/images/chair/chair3.webp",
    category: "chair",
    stock: 10,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 4,
    name: "Winston Rocker",
    description:
      "Elegant rocking chair with a walnut finish and curved ergonomic design.",
    price: 219.99,
    discount: 0,
    image: "/images/chair/chair4.webp",
    category: "chair",
    stock: 0,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 5,
    name: "Harper Task Chair",
    description:
      "Stylish and functional swivel chair with breathable mesh and lumbar support.",
    price: 129.99,
    discount: 50,
    image: "/images/chair/chair5.webp",
    category: "chair",
    stock: 14,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 6,
    name: "Camden Wingback",
    description:
      "Traditional wingback design reimagined with contemporary fabric and high backrest.",
    price: 174.99,
    discount: 20,
    image: "/images/chair/chair6.webp",
    category: "chair",
    stock: 4,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 7,
    name: "Emery Woven Chair",
    description:
      "Rustic farmhouse charm with a woven rattan seat and distressed wood frame.",
    price: 139.99,
    discount: 20,
    image: "/images/chair/chair7.webp",
    category: "chair",
    stock: 9,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Kai Minimalist Chair",
    description:
      "Clean lines and matte black metal legs define this minimalist beauty.",
    price: 114.99,
    discount: 0,
    image: "/images/chair/chair10.webp",
    category: "chair",
    stock: 11,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 12,
    name: "Reese Barrel Chair",
    description:
      "Curved barrel silhouette and plush cushions for cozy reading corners.",
    price: 149.99,
    discount: 10,
    image: "/images/chair/chair12.webp",
    category: "chair",
    stock: 6,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 13,
    name: "Bennett Leather Chair",
    description:
      "Genuine leather and a steel frame combine rugged durability with refined style.",
    price: 239.99,
    discount: 0,
    image: "/images/chair/chair13.webp",
    category: "chair",
    stock: 3,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 14,
    name: "Zane Contemporary Chair",
    description:
      "Bold, boxy design with high-resilience foam for ultimate lounging.",
    price: 199.99,
    discount: 0,
    image: "/images/chair/chair14.webp",
    category: "chair",
    stock: 10,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 15,
    name: "Riley Kids Chair",
    description:
      "Miniature design perfect for kids, made of safe and soft foam padding.",
    price: 59.99,
    discount: 0,
    image: "/images/chair/chair15.webp",
    category: "chair",
    stock: 0,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
];

export const sofas = [
  {
    id: 101,
    name: "Monroe Tufted Sofa",
    description:
      "Chesterfield-inspired sofa with deep button tufting and rolled arms for a classic look.",
    price: 849.99,
    discount: 0,
    image: "/images/sofa/sofa1.webp",
    category: "sofa",
    stock: 5,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 102,
    name: "Harper Sectional",
    description:
      "L-shaped sectional with performance fabric and storage chaise.",
    price: 1199.99,
    discount: 20,
    image: "/images/sofa/sofa2.webp",
    category: "sofa",
    stock: 3,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 103,
    name: "Nico Loveseat",
    description:
      "Compact two-seater with flared arms and a supportive foam seat.",
    price: 599.99,
    discount: 20,
    image: "/images/sofa/sofa3.webp",
    category: "sofa",
    stock: 0,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 104,
    name: "Arlo Sleeper Sofa",
    description:
      "Modern pull-out sofa bed with a memory foam mattress and hidden storage.",
    price: 979.99,
    discount: 20,
    image: "/images/sofa/sofa4.webp",
    category: "sofa",
    stock: 6,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 105,
    name: "Sloan 3-Seater",
    description: "Simple silhouette with elegant piping and removable covers.",
    price: 749.99,
    discount: 20,
    image: "/images/sofa/sofa5.webp",
    category: "sofa",
    stock: 4,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 106,
    name: "Everly Velvet Sofa",
    description:
      "Luxe velvet and gold legs bring glam appeal to your living room.",
    price: 889.99,
    discount: 20,
    image: "/images/sofa/sofa6.webp",
    category: "sofa",
    stock: 5,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 107,
    name: "Milo Mid-Century Sofa",
    description:
      "Tapered legs and tufted back cushions define this retro classic.",
    price: 699.99,
    discount: 20,
    image: "/images/sofa/sofa7.webp",
    category: "sofa",
    stock: 10,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 108,
    name: "Remy Cloud Sofa",
    description:
      "Overstuffed cushions with feather-fill offer unparalleled softness.",
    price: 1299.99,
    discount: 20,
    image: "/images/sofa/sofa8.webp",
    category: "sofa",
    stock: 2,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 109,
    name: "Haven Modular Sofa",
    description:
      "Customizable modular sofa with washable slipcovers and deep seats.",
    price: 1399.99,
    discount: 0,
    image: "/images/sofa/sofa9.webp",
    category: "sofa",
    stock: 0,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 110,
    name: "Ivy Petite Sofa",
    description:
      "Slim profile with rounded arms, ideal for small-space living.",
    price: 1589.99,
    discount: 0,
    image: "/images/sofa/sofa10.webp",
    category: "sofa",
    stock: 6,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 111,
    name: "Dex Reclining Sofa",
    description:
      "Power recliner with USB ports and smooth faux leather upholstery.",
    price: 999.99,
    discount: 0,
    image: "/images/sofa/sofa11.webp",
    category: "sofa",
    stock: 7,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 112,
    name: "Atlas Leather Sofa",
    description:
      "Premium top-grain leather and kiln-dried hardwood frame ensure durability.",
    price: 1599.99,
    discount: 0,
    image: "/images/sofa/sofa12.webp",
    category: "sofa",
    stock: 3,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 113,
    name: "Rowan Studio Sofa",
    description:
      "Studio-style, extra-firm cushions and a modern square silhouette.",
    price: 679.99,
    discount: 10,
    image: "/images/sofa/sofa13.webp",
    category: "sofa",
    stock: 8,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 114,
    name: "Piper Deep Sofa",
    description: "Ultra-deep seat depth perfect for lounging or movie nights.",
    price: 999.99,
    discount: 10,
    image: "/images/sofa/sofa14.webp",
    category: "sofa",
    stock: 4,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 115,
    name: "Wells Convertible Sofa",
    description: "Convertible from sofa to chaise to sleeper in seconds.",
    price: 779.99,
    discount: 20,
    image: "/images/sofa/sofa15.webp",
    category: "sofa",
    stock: 6,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
];

export const lamps = [
  {
    id: 201,
    name: "Luna Glass Table Lamp",
    description:
      "Translucent glass base paired with a linen drum shade for soft ambient light.",
    price: 89.99,
    discount: 20,
    image: "/images/lamp/lamp1.webp",
    category: "lamp",
    stock: 12,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 202,
    name: "Aria Floor Lamp",
    description:
      "Arched metal design with matte black finish and an oversized dome shade.",
    price: 139.99,
    discount: 20,
    image: "/images/lamp/lamp2.webp",
    category: "lamp",
    stock: 7,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 203,
    name: "Nox LED Desk Lamp",
    description:
      "Sleek touch-activated LED lamp with brightness memory and USB charging port.",
    price: 59.99,
    discount: 20,
    image: "/images/lamp/lamp3.webp",
    category: "lamp",
    stock: 20,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 204,
    name: "Cleo Tripod Lamp",
    description:
      "Mid-century inspired tripod legs with a natural wood finish and white linen shade.",
    price: 119.99,
    discount: 20,
    image: "/images/lamp/lamp4.webp",
    category: "lamp",
    stock: 10,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 205,
    name: "Vesper Touch Lamp",
    description:
      "Contemporary design with 3-level dimming and a frosted glass shade.",
    price: 74.99,
    discount: 20,
    image: "/images/lamp/lamp5.webp",
    category: "lamp",
    stock: 14,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 206,
    name: "Nova Rattan Lamp",
    description:
      "Handwoven rattan shade for a warm, natural glow. Great for boho spaces.",
    price: 64.99,
    discount: 20,
    image: "/images/lamp/lamp6.webp",
    category: "lamp",
    stock: 8,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 207,
    name: "Orbit Smart Lamp",
    description:
      "Voice-controlled RGB lamp compatible with Alexa and Google Assistant.",
    price: 89.99,
    discount: 20,
    image: "/images/lamp/lamp7.webp",
    category: "lamp",
    stock: 9,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 208,
    name: "Lyra Industrial Lamp",
    description:
      "Exposed Edison bulb with a pipe-style frame adds an industrial edge.",
    price: 52.99,
    discount: 20,
    image: "/images/lamp/lamp8.webp",
    category: "lamp",
    stock: 11,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 209,
    name: "Atlas Ceramic Lamp",
    description:
      "Sculptural ceramic base in matte white finish with a woven shade.",
    price: 92.99,
    discount: 20,
    image: "/images/lamp/lamp9.webp",
    category: "lamp",
    stock: 13,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
];

export const beds = [
  {
    id: 301,
    name: "Alder Platform Bed",
    description:
      "Solid wood frame with slatted support system — no box spring needed.",
    price: 599.99,
    discount: 20,
    image: "/images/bed/bed1.webp",
    category: "bed",
    stock: 4,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 302,
    name: "Harbor Upholstered Bed",
    description: "Tufted headboard and soft fabric upholstery in slate grey.",
    price: 749.99,
    discount: 10,
    image: "/images/bed/bed2.webp",
    category: "bed",
    stock: 5,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 303,
    name: "Mira Storage Bed",
    description: "Lift-up platform for hidden storage beneath the mattress.",
    price: 849.99,
    discount: 0,
    image: "/images/bed/bed3.webp",
    category: "bed",
    stock: 3,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 304,
    name: "Cora Metal Bed",
    description:
      "Black steel frame with vintage curves and an industrial finish.",
    price: 449.99,
    discount: 20,
    image: "/images/bed/bed4.webp",
    category: "bed",
    stock: 8,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 305,
    name: "Lennox Canopy Bed",
    description:
      "Elegant four-poster bed with minimal lines and matte black finish.",
    price: 899.99,
    discount: 20,
    image: "/images/bed/bed5.webp",
    category: "bed",
    stock: 2,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 306,
    name: "Finley Daybed",
    description:
      "Compact twin daybed with pull-out trundle — ideal for guests.",
    price: 2599.99,
    discount: 0,
    image: "/images/bed/bed6.webp",
    category: "bed",
    stock: 7,
    newArival: true,
    featured: false,
    rating: 4.5,
  },
  {
    id: 307,
    name: "Kira Velvet Bed",
    description: "Velvet-wrapped frame with diamond tufting — luxe and cozy.",
    price: 699.99,
    discount: 20,
    image: "/images/bed/bed7.webp",
    category: "bed",
    stock: 6,
    newArival: false,
    featured: false,
    rating: 4.5,
  },
  {
    id: 308,
    name: "Ashby Twin Bed",
    description: "Simple and sturdy twin-size bed perfect for kids' rooms.",
    price: 399.99,
    discount: 20,
    image: "/images/bed/bed8.webp",
    category: "bed",
    stock: 10,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 309,
    name: "Tessa Low Profile Bed",
    description:
      "Low headboard and sleek frame for a minimalist modern bedroom.",
    price: 629.99,
    discount: 20,
    image: "/images/bed/bed9.webp",
    category: "bed",
    stock: 5,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 310,
    name: "Noor Floating Bed",
    description:
      "Hidden base creates a floating illusion — clean and futuristic.",
    price: 949.99,
    discount: 20,
    image: "/images/bed/bed10.webp",
    category: "bed",
    stock: 3,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 311,
    name: "Weston Panel Bed",
    description: "Classic panel design with subtle molding — timeless appeal.",
    price: 589.99,
    discount: 20,
    image: "/images/bed/bed11.webp",
    category: "bed",
    stock: 6,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
];
export const tables = [
  {
    id: 401,
    name: "Ellis Round Dining Table",
    description:
      "Mid-century modern design with walnut finish and angled legs.",
    price: 499.99,
    discount: 20,
    image: "/images/table/table1.webp",
    category: "table",
    stock: 6,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 402,
    name: "Orion Glass Coffee Table",
    description:
      "Tempered glass top with a gold steel frame — light and elegant.",
    price: 239.99,
    discount: 20,
    image: "/images/table/table2.webp",
    category: "table",
    stock: 10,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 403,
    name: "Noah Extendable Dining Table",
    description: "Seats 4–8 with hidden leaf extension. Oak veneer surface.",
    price: 699.99,
    discount: 20,
    image: "/images/table/table3.webp",
    category: "table",
    stock: 4,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 404,
    name: "Iris Marble Console Table",
    description:
      "White marble top with black iron frame — perfect for entryways.",
    price: 329.99,
    discount: 20,
    image: "/images/table/table4.webp",
    category: "table",
    stock: 7,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 405,
    name: "Theo Nesting table (Set of 2)",
    description:
      "Minimalist nesting design with ash wood tops and powder-coated legs.",
    price: 179.99,
    discount: 0,
    image: "/images/table/table5.webp",
    category: "table",
    stock: 12,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 406,
    name: "Kai Lift-Top Coffee Table",
    description: "Hidden storage compartment with lift-up work surface.",
    price: 279.99,
    discount: 0,
    image: "/images/table/table6.webp",
    category: "table",
    stock: 5,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 407,
    name: "Zane Outdoor Dining Table",
    description: "Weather-resistant teak finish with slatted top for drainage.",
    price: 559.99,
    discount: 0,
    image: "/images/table/table7.webp",
    category: "table",
    stock: 3,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 408,
    name: "Milo Side Table",
    description: "Compact accent table with two-tier open shelf design.",
    price: 89.99,
    discount: 0,
    image: "/images/table/table8.webp",
    category: "table",
    stock: 15,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 409,
    name: "Sierra Farmhouse Table",
    description: "Rustic reclaimed pine wood with trestle-style legs.",
    price: 849.99,
    discount: 0,
    image: "/images/table/table9.webp",
    category: "table",
    stock: 2,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 410,
    name: "Wren Foldable Table",
    description:
      "Space-saving folding table ideal for apartments or pop-up use.",
    price: 3999.99,
    discount: 0,
    image: "/images/table/table10.webp",
    category: "table",
    stock: 9,
    newArival: true,
    featured: true,
    rating: 4.5,
  },
  {
    id: 411,
    name: "Nova Writing Desk",
    description: "Modern writing desk with slim drawers and oak finish.",
    price: 800,
    discount: 0,
    image: "/images/table/table11.webp",
    category: "table",
    stock: 6,
    newArival: true,
    featured: true,
    rating: 4.5,
  },
  {
    id: 412,
    name: "Atlas Bar Table",
    description: "Tall, narrow bar-height table perfect for small kitchens.",
    price: 299.99,
    discount: 0,
    image: "/images/table/table12.webp",
    category: "table",
    stock: 8,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 413,
    name: "Kendall Drop Leaf Table",
    description:
      "Foldable sides and compact footprint with hidden storage drawers.",
    price: 399.99,
    discount: 0,
    image: "/images/table/table13.webp",
    category: "table",
    stock: 5,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 414,
    name: "Echo Round Bistro Table",
    description: "Ideal for cafés or patios, with a concrete finish top.",
    price: 289.99,
    discount: 0,
    image: "/images/table/table14.webp",
    category: "table",
    stock: 7,
    newArival: false,
    featured: true,
    rating: 4.5,
  },
  {
    id: 415,
    name: "Riley Kids Activity Table",
    description:
      "Rounded edges, storage bins, and wipeable top for mess-free fun.",
    price: 179.99,
    discount: 0,
    image: "/images/table/table15.webp",
    category: "table",
    stock: 11,
    newArival: true,
    featured: true,
    rating: 4.5,
  },
];

export const products = [...chairs, ...sofas, ...lamps, ...beds, ...tables];
